spring:
  profiles:
    default: dev
  thymeleaf:
    cache: false
    prefix: file:calendar-api/src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0

  datasource:
    url: jdbc:mysql://localhost:3366/calendar_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always

# SQL parameter logging
logging:
  level:
    me.ezra: TRACE
    org.springframework.web: TRACE
